# Generated by Django 5.2.8 on 2025-12-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_tag_alter_page_audio_book_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='books', to='book.tag'),
        ),
    ]
