# Generated by Django 5.2.8 on 2025-12-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentary',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='documentaries/audio/'),
        ),
        migrations.AddField(
            model_name='documentary',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentary',
            name='image',
            field=models.ImageField(upload_to='documentaries/images/'),
        ),
    ]
